### ISSUE TITLE
Double down on mentioning the second section should be done in Markdown

### ISSUE THREAD

**Issue by kellyeryan** [powerhome/phrg-github-workflow-primer-part-four#2]
Also - add a link to this useful Markdown preview page - https://dillinger.io/

Maybe also mention to leverage the Ruby docs to discover some "favorite" Ruby methods, and add a link.

**Comment by kellyeryan** [comment]
@garettarrowood

**Comment by garettarrowood** [comment]
Resolved with https://github.com/powerhome/phrg-github-workflow-primer-part-four/commit/dc947dc6928fd5a223f887f7d7aaa32e5940872f . Thank you!
